[2023-03-28 09:10:13 +0000] [278458] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/code/floorwalk/dashboard
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: myapp.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f6ce15ff520>
  on_reload: <function OnReload.on_reload at 0x7f6ce15ff640>
  when_ready: <function WhenReady.when_ready at 0x7f6ce15ff760>
  pre_fork: <function Prefork.pre_fork at 0x7f6ce15ff880>
  post_fork: <function Postfork.post_fork at 0x7f6ce15ff9a0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f6ce15ffac0>
  worker_int: <function WorkerInt.worker_int at 0x7f6ce15ffbe0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f6ce15ffd00>
  pre_exec: <function PreExec.pre_exec at 0x7f6ce15ffe20>
  pre_request: <function PreRequest.pre_request at 0x7f6ce15fff40>
  post_request: <function PostRequest.post_request at 0x7f6ce0f30040>
  child_exit: <function ChildExit.child_exit at 0x7f6ce0f30160>
  worker_exit: <function WorkerExit.worker_exit at 0x7f6ce0f30280>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f6ce0f303a0>
  on_exit: <function OnExit.on_exit at 0x7f6ce0f304c0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-28 09:10:13 +0000] [278458] [INFO] Starting gunicorn 20.1.0
[2023-03-28 09:10:13 +0000] [278458] [DEBUG] Arbiter booted
[2023-03-28 09:10:13 +0000] [278458] [INFO] Listening at: http://127.0.0.1:8000 (278458)
[2023-03-28 09:10:13 +0000] [278458] [INFO] Using worker: sync
[2023-03-28 09:10:13 +0000] [278459] [INFO] Booting worker with pid: 278459
[2023-03-28 09:10:13 +0000] [278459] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myapp'
[2023-03-28 09:10:13 +0000] [278459] [INFO] Worker exiting (pid: 278459)
[2023-03-28 09:10:13 +0000] [278458] [INFO] Shutting down: Master
[2023-03-28 09:10:13 +0000] [278458] [INFO] Reason: Worker failed to boot.
